### ISSUE TITLE
Compilation fails: undefined reference to XOpenDisplay

### ISSUE THREAD

**Issue by Fifis** [perk11/runwhenidle#1]
System: Linux Mint 21.1 based on Ubuntu 22.04 LT

I have `build-essential`, `libxss1`, `libxss-dev` (both v. 1:1.2.3-1build2), and `gcc` installed. Still, `make release` won’t compile:

```
gcc -o runwhenidle -O3  -lXss -lX11 main.c
/usr/bin/ld: /tmp/ccCESovs.o: in function `main':
main.c:(.text.startup+0x209): undefined reference to `XOpenDisplay'
/usr/bin/ld: main.c:(.text.startup+0x21a): undefined reference to `XScreenSaverAllocInfo'
/usr/bin/ld: main.c:(.text.startup+0x264): undefined reference to `XScreenSaverQueryInfo'
collect2: error: ld returned 1 exit status
make: *** [Makefile:13: executable] Error 1
```

How can this be fixed?

**Comment by vimpostor** [comment]
Does it compile if you use `gcc -lXss $(pkg-config --cflags x11 --libs x11) main.c -o runwhenidle` instead?

If yes, what is the output of `pkg-config --cflags x11 --libs x11`?

**Comment by perk11** [comment]
My bad, I shouldn't have written a Makefile from scratch, some versions of gcc ignore -l flags if it's before the path to the source code. This is now fixed, it compiled in an LXC container with Ubuntu 22.04 for me.
